name: app_actasalinstante
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  get: ^4.1.4
  http: ^0.13.3
  flutter_staggered_grid_view: ^0.4.0
  
  carousel_slider: ^3.0.0
  hexcolor: ^2.0.4
  font_awesome_flutter: ^9.1.0
  otp_text_field: ^1.1.1
  flutter_svg: ^1.1.0
  image_picker: ^0.8.5+3
  searchfield: ^0.6.6
  lottie: ^1.3.0
  giffy_dialog: ^1.8.0

  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  excel:
    git:
      url: "https://github.com/justkawal/excel.git"
      ref: "null-safety"
  cupertino_icons: ^1.0.0
  animated_background: ^2.0.0
  awesome_snackbar_content: ^0.0.5
  socket_io_client: ^2.0.0
  path_provider: ^2.0.11
  get_it: ^7.2.0
  shared_preferences: ^2.0.15
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  table_calendar: ^2.2.3
  responsive_framework: ^0.2.0
  date_field: ^3.0.1
  image_downloader: ^0.31.0
  flutter_file_downloader: ^1.1.0+1
  
  flutter_local_notifications: ^9.7.0
  timezone: ^0.8.0
  rxdart: ^0.27.4
  awesome_notifications: ^0.0.6+11
  android_intent: ^2.0.2
  url_launcher: ^6.1.5
  permission_handler: ^10.0.0
  awesome_dialog: ^1.3.2
  commons: ^0.2.3
  syncfusion_flutter_datagrid: ^20.2.39
  ionicons: ^0.1.2
  unicons: ^2.1.0
  advance_notification: ^1.0.6
  open_filex: ^3.4.0
  animations: ^2.0.3
  flutter_easyloading: ^3.0.5
  google_fonts: ^3.0.1
  blurrycontainer: ^1.0.2
  flutter_contacts: ^1.1.5
  im_animations: ^0.1.2
  dio: ^4.0.6
  geocoding: ^2.0.5
  geolocator: ^9.0.1
  connection_status_bar: ^1.1.6
  check_vpn_connection: ^0.0.2
  intl_phone_field: ^3.1.0
  flutter_html: ^0.11.1
  flutter_tts: ^3.6.1
  syncfusion_flutter_datagrid_export: ^20.3.58-beta
  pie_chart: ^5.3.2
  percent_indicator: ^4.2.2
  

  

  
  
  
 
  
 
  
  
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter
 
  provider: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/welcome.png
    - assets/logo.png
    - assets/MATRIMONIO.jpg
    - assets/DEFUNCION.jpg
    - assets/NACIMIENTO.jpg
    - assets/RFC.jpg
    - assets/icons/Camera Icon.svg
    - assets/loginuser.png
    - assets/ACTAS.json
    - assets/coffeesplash.json
    - assets/splash.png
    - assets/NAC.png
    - assets/rfc.png
    - assets/Filter.svg
    - assets/Search.svg
    - assets/actas.gif
    - assets/rfc.gif
    - assets/Cadena.gif
    - assets/BusquedaCurp.gif
    - assets/datosP.gif
    - assets/Civil.gif
    - assets/matrimonio.png
    - assets/divorcio.png
    - assets/desconocido.png
    - assets/LogImage.gif
    - assets/new.gif
    - assets/particles.gif
    - assets/error.gif
    - assets/login.json
    - assets/fondoalterno.jpg
    - assets/pdf.gif
    - assets/close.gif
    - assets/Principal.gif
    - assets/error404.gif
    - assets/ststus_close.gif
    - assets/ststus_ok.gif
    - assets/NEW_Acta.png
    - assets/NEW_RFC.png
    - assets/Villaflores.png
    - assets/BOCHIL.png
    - assets/Toluca.jpeg
    - assets/Civil.jpeg
    
    
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
flutter_icons:
 android: true
 ios: true
 image_path: "assets/splash.png" 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
